spring.application.name=payment-processing-api

server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/payment_processing
spring.datasource.username=postgres
spring.datasource.password=Flavio@Booking2026!

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.flyway.enabled=true

springdoc.swagger-ui.path=/swagger-ui.html

management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=always

jwt.secret=Y2hhbmdlLXRoaXMtc2VjcmV0LWtleS1mb3ItcHJvZHVjdGlvbi0xMjM0NTY=
jwt.expiration=86400000

spring.data.redis.host=localhost
spring.data.redis.port=6379

spring.kafka.bootstrap-servers=localhost:9092

spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer